language: java
deploy:
  provider: heroku
  api_key:
    secure: P/0JcpjSYSaanrKDXLPxvRqICz66VAzFbzzyVJheMv0PKb531TL6lfeCURhRtlCp0jvShfiQLh8AVGfBLHRuSprYvHDHGCBIeSHO9LNr1ezQwCQadgxuEK0eAEXqN02rxOMAK/4r9TQyO4iNwPSJo33ISBGVBFMR9VyqtEZ3lVTEyCr2skEE1v24yebV04GVTDydBTzMxn2rZvBu6Zmj5bYYKhNa0L0W0PDYPktDoyRxP3xVVNwZbvLI3FZBYMtAFEXZEBWErlI5LL51JQXrfRU4DNwmdIrL1TRpR6naT1c1OLxuuCt/PnIf9YBMbVWAoFdCCLgGnslIUm+/Bwf8gkj0WUVvWHwP4Ddk61yhcHV1WNe6n016MG9dP1KqiJrhw3SE4UEVa5L58BOp+HhBS2HN90o2dEzJx2Pf4jj9Amn/Gjr37wkbNWelXNeL3TmxQ5h9U7Pjb9gzclHRwfept/LAQIQolf9o27/mLgYY/Gi2Tbkm5uRD3ZJKkbVka7cr45COVJ3IhiuA4LX3uWPwigTIZeSjBFd4XQvDTHU1b+EzjN7tiJfqmhRz0xhg16laMLC25+AbwLeMqQS7qa3OE3ZUYRgEebGYyV2A0aKmJ/qXfxEwQtNCeNHiS7RlgQ0AjzocXvayzUhazslxqH70sgaK8uAIuCrv9r7zNetSYEo=
  app: sundarban-kartik-app
